// <auto-generated />
using System;
using BiteRush.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BiteRuch.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20260511205932_seeds")]
    partial class seeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BiteRush.Models.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvaiable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            ImageUrl = "/images/menuitems/koshary.jpg",
                            IsAvaiable = true,
                            Name = "Koshary",
                            Price = 40.0,
                            RestaurantId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222224"),
                            ImageUrl = "/images/menuitems/falafel.jpg",
                            IsAvaiable = true,
                            Name = "Falafel",
                            Price = 30.0,
                            RestaurantId = new Guid("11111111-1111-1111-1111-111111111113")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            ImageUrl = "/images/menuitems/grilledchicken.jpg",
                            IsAvaiable = true,
                            Name = "Grilled Chicken",
                            Price = 120.0,
                            RestaurantId = new Guid("11111111-1111-1111-1111-111111111114")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222225"),
                            ImageUrl = "/images/menuitems/molokhia.jpg",
                            IsAvaiable = true,
                            Name = "Molokhia",
                            Price = 50.0,
                            RestaurantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222226"),
                            ImageUrl = "/images/menuitems/kebab.jpg",
                            IsAvaiable = true,
                            Name = "Kebab",
                            Price = 60.0,
                            RestaurantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("BiteRush.Models.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(303)
                        .HasColumnType("nvarchar(303)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Trendy Cairo eatery",
                            ImageUrl = "/images/restaurants/cairobites.jpg",
                            Latitude = 30.0444,
                            Longitude = 31.235700000000001,
                            Name = "Cairo Bites",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            Description = "Classic Nile-side grill",
                            ImageUrl = "/images/restaurants/nilegrill.jpg",
                            Latitude = 30.050000000000001,
                            Longitude = 31.2333,
                            Name = "Nile Grill",
                            Rating = 4.2000000000000002
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            Description = "Famous Egyptian street food spot serving authentic koshary.",
                            ImageUrl = "/images/restaurants/koshary.jpg",
                            Latitude = 30.0444,
                            Longitude = 31.235700000000001,
                            Name = "Koshary El Tahrir",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            Description = "Trendy Egyptian restaurant offering modern takes on local dishes.",
                            ImageUrl = "/images/restaurants/zooba.jpg",
                            Latitude = 30.045000000000002,
                            Longitude = 31.236000000000001,
                            Name = "Zooba",
                            Rating = 4.2000000000000002
                        });
                });

            modelBuilder.Entity("BiteRush.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BiteRush.Models.MenuItem", b =>
                {
                    b.HasOne("BiteRush.Models.Restaurant", null)
                        .WithMany("MenuItems")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BiteRush.Models.Restaurant", b =>
                {
                    b.Navigation("MenuItems");
                });
#pragma warning restore 612, 618
        }
    }
}
